title: Dev meets Contact-Center
title_separator: "-"
locale: en-GB
description: "Developer's journey into Contact-Center"
favicon: "/assets/images/logo.png"
avatar: "/assets/images/logo.png"
comments: false
url: https://devmeetscontactcenter.com
atom_feed:
  path: # blank (default) uses feed.xml

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site Author
author:
  name: "Dev Meets Contact-Center" # appears in the footer and atom feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:title.html

# Without this building the website fails, saying it can't find the
# Primer theme - which is correct as I removed all themes from the
# Gemfile.lock when GitHub complained that the Primer theme wasn't
# supported and yet kept being used as a theme in spite of any config
# in here
theme:
